-- PostgreSQL: ejecutar manualmente en la base de demostración antes del primer arranque actualizado.
-- Revisar y respaldar la base antes de una migración. Este script no se ejecuta desde los tests.
-- No elimina pedidos, pagos ni reservas. Ante duplicados u orfandad se detiene para revisión.
BEGIN;

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pagos GROUP BY pedido_id HAVING COUNT(*) > 1) THEN
        RAISE EXCEPTION 'Hay varios pagos para un pedido. Revisar antes de imponer unicidad.';
    END IF;
    IF EXISTS (SELECT 1 FROM pagos pg LEFT JOIN pedidos p ON p.id = pg.pedido_id WHERE p.id IS NULL) THEN
        RAISE EXCEPTION 'Hay pagos de pedidos inexistentes. Revisar los registros históricos.';
    END IF;
END $$;

ALTER TABLE pagos ALTER COLUMN metodo DROP NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS ux_pagos_pedido_id ON pagos(pedido_id);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_pagos_pedido_tb2'
        AND conrelid = 'pagos'::regclass) THEN
        ALTER TABLE pagos ADD CONSTRAINT fk_pagos_pedido_tb2 FOREIGN KEY (pedido_id) REFERENCES pedidos(id);
    END IF;
END $$;

ALTER TABLE pedidos ADD COLUMN IF NOT EXISTS direccion_entrega VARCHAR(255);
ALTER TABLE detalles_pedido ADD COLUMN IF NOT EXISTS precio_unitario NUMERIC(10,2);
UPDATE detalles_pedido SET precio_unitario = ROUND(subtotal / cantidad, 2)
WHERE precio_unitario IS NULL AND cantidad > 0;

ALTER TABLE reservas ADD COLUMN IF NOT EXISTS motivo_rechazo VARCHAR(300);
ALTER TABLE reservas ADD COLUMN IF NOT EXISTS version BIGINT NOT NULL DEFAULT 0;
UPDATE reservas SET version = 0 WHERE version IS NULL;
ALTER TABLE reservas ALTER COLUMN version SET DEFAULT 0;
ALTER TABLE reservas ALTER COLUMN version SET NOT NULL;

CREATE TABLE IF NOT EXISTS notificaciones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL,
    mensaje VARCHAR(500) NOT NULL,
    fecha_creacion TIMESTAMP NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_notificaciones_usuario_fecha ON notificaciones(usuario_id, fecha_creacion DESC);

COMMIT;
