server:
  port: 8081

spring:
  application:
    name: RestoPilot API
  datasource:
    url: jdbc:postgresql://localhost:5432/restopilot_db
    username: postgres
    password: Andre1808
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  # Clave secreta HMAC en Base64
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  # Tiempo de vida del token 24 horas
  expiration: 86400000